#################################################################################
# Node-RED + InfluxDB + Grafana Stack or Compose
#################################################################################
# docker stack deploy enviro-collector-backedn --compose-file docker-compose.yml
# docker-compose -f docker-compose.yml -p enviro-collector-backend up
#################################################################################
version: "3.1"

services:

  # InfluxDB container:
  influxdb:
    image: influxdb
    container_name: enviro-backend-influxdb
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_DB=sensors
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminPassw0rd
    ports:
      - "8086:8086"
      - "2003:2003"
    volumes:
      - enviro-backend-influxdb-data:/var/lib/influxdb

  # Node-RED container:
  node-red:
    image: nodered/node-red:latest
    container_name: enviro-backend-node-red
    environment:
      - TZ=Europe/Madrid
      - FLOWS=/etc/enviro/flows/influxdb.json
    ports:
      - "1880:1880"
    volumes:
      - enviro-backend-node-red-data:/data
      - ./node-red/settings.js:/data/settings.js
      - ./node-red/flows:/etc/enviro/flows
    depends_on:
      - influxdb
    links:
      - "influxdb:influxdb"

  # Grafana Container
  grafana:
    image: grafana/grafana
    container_name: enviro-backend-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminPassw0rd
      - GF_PATHS_PROVISIONING=./grafana
    ports:
      - "3000:3000"
    volumes:
      - enviro-backend-grafana-data:/var/lib/grafana
      - ./grafana/datasources:/usr/share/grafana/grafana/datasources
      - ./grafana/dashboards:/usr/share/grafana/grafana/dashboards
    depends_on:
      - influxdb
    links:
      - "influxdb:influxdb"

# Volumes
volumes:
  enviro-backend-node-red-data:
  enviro-backend-influxdb-data:
  enviro-backend-grafana-data:
