#################################################################################
# Node-RED + InfluxDB + Grafana Stack or Compose
#################################################################################
# docker stack deploy enviro-collector-backedn --compose-file docker-compose.yml
# docker-compose -f docker-compose.yml -p enviro-collector-backend up
#################################################################################
version: "3.1"

services:

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: always
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "443:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  # InfluxDB container:
  influxdb:
    image: influxdb
    container_name: enviro-backend-influxdb
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_DB=sensors
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=9874292et56
    expose:
      - "8086"
    volumes:
      - enviro-backend-influxdb-data:/var/lib/influxdb

  # Node-RED container:
  node-red:
    image: nodered/node-red:latest
    container_name: enviro-backend-node-red
    environment:
      - TZ=Europe/Madrid
      - FLOWS=/etc/enviro/flows/influxdb.json
    expose:
      - "1880"
    volumes:
      - enviro-backend-node-red-data:/data
      - ./node-red/settings.js:/data/settings.js
      - ./node-red/flows:/etc/enviro/flows
    depends_on:
      - influxdb
    links:
      - "influxdb:influxdb"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node-red.rule=PathPrefix(`/nodered`)"
      - "traefik.http.routers.node-red.entrypoints=web"

  # Grafana Container
  grafana:
    image: grafana/grafana
    container_name: enviro-backend-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=9874292et56
      - GF_PATHS_PROVISIONING=./grafana
      - GF_SERVER_DOMAIN=ilab.clece.es/grafana
      - GF_SERVER_ROOT_URL=http://ilab.clece.es/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    expose:
      - "3000"
    volumes:
      - enviro-backend-grafana-data:/var/lib/grafana
      - ./grafana/datasources:/usr/share/grafana/grafana/datasources
      - ./grafana/dashboards:/usr/share/grafana/grafana/dashboards
    depends_on:
      - influxdb
    links:
      - "influxdb:influxdb"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=PathPrefix(`/grafana`)"
      - "traefik.http.routers.grafana.entrypoints=web"

# Volumes
volumes:
  enviro-backend-node-red-data:
  enviro-backend-influxdb-data:
  enviro-backend-grafana-data:
