apiVersion: 1

datasources:

  - name: InfluxDB
    type: influxdb
    access: proxy
    database: sensors
    user: admin
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      httpMode: POST
    secureJsonData:
      password: adminPassw0rd
